name: Check dbt Debug Connectivity

on:
  push:
    branches:
      - snowflake-etl-test

jobs:
  debug_connectivity:
    runs-on: windows-latest # Change this to run on Windows

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Check dbt Debug Connectivity
      run: dbt debug
